export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'lOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}
export const userConstant = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}
export const categoryConstant = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstant = {
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE"
}
export const initialDataConstant = {
    GET_ALL_INITIALDATA_REQUEST: 'GET_ALL_INITIALDATA_REQUEST',
    GET_ALL_INITIALDATA_SUCCESS: 'GET_ALL_INITIALDATA_SUCCESS',
    GET_ALL_INITIALDATA_FAILURE: 'GET_ALL_INITIALDATA_FAILURE',
}